### ISSUE TITLE
fill method fails when using strict mode

### ISSUE THREAD

**Issue by almarro1** [Bajix/mongoose-fixture-factory#1]
I'm using this library in some test cases executed with mocha. Each test case loads the library and registers different models and fixtures. All my js code is written using 'use strict'; directive.

When tests are executed, (I have before(Factory.fill); hook for each test case), that before hook fails.
After investigating a little bit, it is due to a bug in the method, as you make use of a variable that is not initialized because of a missing comma. The specific code is:

function fill( cb ) {
  async.each(Object.keys(models), function( key, cb ) {
    var fixtures = store[key]   <=== you need a comma here, otherwise JS throws an error
      Model = models[key];

**Comment by Bajix** [comment]
Ah, thanks for pointing that out - the tests weren't running in strict mode and I hadn't noticed. I published a new release
